"""
detector.py
Infers problem type (classification, regression, clustering) from audit data.
"""

def run_detector(audit, force_type=None, _auto_input=None):
    """
    Analyzes the audit object to determine the ML problem type.

    Parameters
    ----------
    audit : dict
        The audit object generated by Person 1.
    force_type : str, optional
        User override ('classification', 'regression', 'clustering').
    _auto_input : str, optional
        Used for automated testing to mock user input.

    Returns
    -------
    detection : dict
        The detection object required by downstream modules.
    """
    print("\n[DETECTION]")

    target = audit.get('target_column')
    target_dtype = audit.get('target_dtype')
    n_unique = audit.get('target_unique_values', 0)
    shape = audit.get('shape', (0, 0))
    n_rows = shape[0]

    detection = {
        'problem_type': 'unknown',
        'detection_method': 'inferred',
        'confidence': 'low',
        'classification_subtype': None,
        'num_classes': None,
        'class_labels': None,
        'metrics_averaging': None,
        'regression_subtype': 'standard',
        'target_log_transform': False,
        'signals': {}
    }

    if force_type is not None:
        if force_type not in ['classification', 'regression', 'clustering']:
            raise ValueError(f"Invalid force_type: {force_type}")
        detection['problem_type'] = force_type
        detection['detection_method'] = 'user_flag'
        detection['confidence'] = 'high'
        print(f"  -> Problem type inferred as: {force_type.capitalize()} (User override)")
        return detection

    if target is None:
        detection['problem_type'] = 'clustering'
        detection['confidence'] = 'high'
        detection['signals']['target_column'] = {'value': None, 'vote': 'clustering', 'weight': 5.0}
        print("  -> Problem type inferred as: Clustering (No target column found)")
        return detection

    # Heuristic scoring
    cls_score = 0.0
    reg_score = 0.0

    # 1. Unique values signal
    unique_ratio = (n_unique / n_rows) if n_rows > 0 else 0
    if n_unique <= 20 or unique_ratio < 0.05:
        detection['signals']['unique_values'] = {'value': n_unique, 'vote': 'classification', 'weight': 2.0}
        cls_score += 2.0
        print(f"  -> Signal 1 - Unique values : {n_unique} unique out of {n_rows} rows -> Classification (+2.0)")
    else:
        detection['signals']['unique_values'] = {'value': n_unique, 'vote': 'regression', 'weight': 2.0}
        reg_score += 2.0
        print(f"  -> Signal 1 - Unique values : {n_unique} unique out of {n_rows} rows -> Regression (+2.0)")

    # 2. Dtype signal
    if target_dtype in ['object', 'category', 'bool', 'string']:
        detection['signals']['dtype'] = {'value': target_dtype, 'vote': 'classification', 'weight': 2.0}
        cls_score += 2.0
        print(f"  -> Signal 2 - Dtype         : {target_dtype} -> Classification (+2.0)")
    elif target_dtype in ['float64', 'float32']:
        detection['signals']['dtype'] = {'value': target_dtype, 'vote': 'regression', 'weight': 2.0}
        reg_score += 2.0
        print(f"  -> Signal 2 - Dtype         : {target_dtype} -> Regression (+2.0)")
    elif target_dtype in ['int64', 'int32']:
        if n_unique <= 20: # combine with cardinality
            detection['signals']['dtype'] = {'value': target_dtype, 'vote': 'classification', 'weight': 1.5}
            cls_score += 1.5
            print(f"  -> Signal 2 - Dtype         : {target_dtype} (low cardinality) -> Classification (+1.5)")
        else:
            detection['signals']['dtype'] = {'value': target_dtype, 'vote': 'regression', 'weight': 1.5}
            reg_score += 1.5
            print(f"  -> Signal 2 - Dtype         : {target_dtype} (high cardinality) -> Regression (+1.5)")
    else:
        print(f"  -> Signal 2 - Dtype         : {target_dtype} -> Unknown (+0.0)")

    # 3. Distribution signal
    target_dist = audit.get('target_distribution', {})
    if target_dist:
        num_dist_keys = len(target_dist)
        # If values cluster into distinct counts (few categories) -> classification
        # If it's a very long dict, it's a continuous spread -> regression
        if num_dist_keys <= 20: # basic heuristic
            detection['signals']['distribution'] = {'value': num_dist_keys, 'vote': 'classification', 'weight': 1.0}
            cls_score += 1.0
            print(f"  -> Signal 3 - Distribution  : {num_dist_keys} distinct peaks -> Classification (+1.0)")
        else:
            detection['signals']['distribution'] = {'value': num_dist_keys, 'vote': 'regression', 'weight': 1.0}
            reg_score += 1.0
            print(f"  -> Signal 3 - Distribution  : Continuous spread ({num_dist_keys} values) -> Regression (+1.0)")
    else:
        print(f"  -> Signal 3 - Distribution  : Not provided -> Unknown (+0.0)")

    # 4. Column name heuristic signal
    target_lower = target.lower()
    class_keywords = ['is_', 'has_', 'was_', 'category', 'class', 'label', 'type', 'status', 'churn', 'fraud', 'survived', 'diagnosis', 'default', 'outcome', 'flag']
    reg_keywords = ['price', 'cost', 'revenue', 'amount', 'score', 'rate', 'value', 'age', 'count', 'quantity', 'duration', 'temperature', 'salary', 'weight', 'height']
    
    if any(p in target_lower for p in class_keywords):
        detection['signals']['name_heuristic'] = {'value': target, 'vote': 'classification', 'weight': 1.0}
        cls_score += 1.0
        print(f"  -> Signal 4 - Column name   : '{target}' matches classification keywords -> Classification (+1.0)")
    elif any(p in target_lower for p in reg_keywords):
        detection['signals']['name_heuristic'] = {'value': target, 'vote': 'regression', 'weight': 1.0}
        reg_score += 1.0
        print(f"  -> Signal 4 - Column name   : '{target}' matches regression keywords -> Regression (+1.0)")
    else:
        print(f"  -> Signal 4 - Column name   : '{target}' matches no keywords -> Unknown (+0.0)")

    print(f"  -> Classification score : {cls_score}")
    print(f"  -> Regression score     : {reg_score}")

    # Confidence calculation
    total_score = cls_score + reg_score
    if total_score > 0:
        max_score = max(cls_score, reg_score)
        confidence_ratio = max_score / total_score
        detection['confidence'] = 'high' if confidence_ratio >= 0.7 else ('medium' if confidence_ratio >= 0.55 else 'low')
    else:
        detection['confidence'] = 'low'
        confidence_ratio = 0.5

    # Decision & Ambiguity handling
    if cls_score == reg_score or detection['confidence'] == 'low':
        print(f"\n  -> Low confidence decision. Scores: Classification={cls_score} | Regression={reg_score}")
        print(f"  -> Please confirm problem type:")
        print(f"     (1) Classification")
        print(f"     (2) Regression")
        if _auto_input:
            choice = _auto_input
            print(f"  -> Your choice (auto): {choice}")
        else:
            try:
                choice = input("  -> Your choice: ").strip()
            except EOFError:
                # Fallback for environments where input() is not supported and no _auto_input provided
                choice = '1' if cls_score >= reg_score else '2'
                print(f"  -> Your choice (auto-fallback): {choice}")
        if choice == '1':
            detection['problem_type'] = 'classification'
            detection['detection_method'] = 'user_confirmed'
            detection['confidence'] = 'high'
        elif choice == '2':
            detection['problem_type'] = 'regression'
            detection['detection_method'] = 'user_confirmed'
            detection['confidence'] = 'high'
        else:
            # Default fallback if user types gibberish
            detection['problem_type'] = 'classification' if cls_score >= reg_score else 'regression'
            detection['detection_method'] = 'inferred_fallback'
    else:
        detection['problem_type'] = 'classification' if cls_score > reg_score else 'regression'

    # Subtype calculations
    if detection['problem_type'] == 'classification':
        dist = audit.get('target_distribution', {})
        num_classes = len(dist) if dist else (n_unique if n_unique > 0 else 2) # safe fallback
        
        detection['num_classes'] = num_classes
        detection['class_labels'] = [str(k) for k in dist.keys()] if dist else [str(i) for i in range(num_classes)]
        
        if num_classes == 2:
            detection['classification_subtype'] = 'binary'
            detection['metrics_averaging'] = 'binary'
        elif 3 <= num_classes <= 15:
            detection['classification_subtype'] = 'multiclass'
            detection['metrics_averaging'] = 'weighted'
        else:
            detection['classification_subtype'] = 'many_class'
            detection['metrics_averaging'] = 'weighted'
            print(f"  -> Warning: many_class subtype detected ({num_classes} classes). Proceed with caution.")
    else: # Regression
        target_stats = audit.get('stats', {}).get(target, {})
        t_min = target_stats.get('min', None)
        t_max = target_stats.get('max', None)
        
        if t_min is not None and t_max is not None:
            if 0.0 <= t_min and t_max <= 1.0:
                detection['regression_subtype'] = 'probability'
                print("  -> Target appears to be a probability (0-1 range)")
            elif t_min >= 0.0:
                detection['regression_subtype'] = 'bounded_positive'
            else:
                detection['regression_subtype'] = 'unbounded'
        else:
            detection['regression_subtype'] = 'standard'
            
        target_skews = audit.get('skewed_columns', {}).get(target, {})
        if target_skews.get('action') == 'log_transform':
            detection['target_log_transform'] = True
            print("  -> Log-transformed target detected. Will back-transform for metrics.")

    print(f"  -> Problem type inferred as: {detection['problem_type'].capitalize()} ({detection['confidence']} confidence)")

    return detection
